
server:
  port: 8090

spring:
  application:
    name: Sample Crud API

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/SB_CRUD_SAMPLE
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgresSQLDialect
      enable_Lazy_Load_no_trans: true

    show-sql: true
    open-in-view: false

springdoc:
  api-docs:
    enabled: true